---
root: true

plugins:
  - '@typescript-eslint'
  - import

extends:
  - airbnb
  - 'plugin:prettier/recommended'
  - prettier
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/typescript'

parser: '@typescript-eslint/parser'

env:
  browser: true
  node: true
  jest: true

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  react/jsx-filename-extension: [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  '@typescript-eslint/explicit-function-return-type': 0
  no-use-before-define: 0
  '@typescript-eslint/no-use-before-define': 0
